### ISSUE TITLE
Simplifying function calls

### ISSUE THREAD

**Issue by teemuvirkkala** [MikelThief/Penguins_Galore#7]
We should probably look into how to simplify the function calls. The current way I coded most of them is pretty horrible.

One way is to use other functions to call those (As in MoveForUser.c). One way could also be defining macros to main.h and use those for example:

```
main.h:
#define PengSE(x,y) MovePengSE(x, y, NumberOfRows, NumberOfColumns, FishArray, AllPengs, PengArray)

main.c:
PengSE(1,1);
```

But there probably should be a better way to do it. Using macro's just seems to be a way to cover the bad coding.

**Comment by MikelThief** [comment]
Done by requesting only PengID, number of Spaces and Direction (Dir)
